Document: spdk
Title: Debian spdk Manual
Author: <insert document author here>
Abstract: This manual describes what spdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spdk/spdk.sgml.gz

Format: postscript
Files: /usr/share/doc/spdk/spdk.ps.gz

Format: text
Files: /usr/share/doc/spdk/spdk.text.gz

Format: HTML
Index: /usr/share/doc/spdk/html/index.html
Files: /usr/share/doc/spdk/html/*.html
